# Database
dbname: ap_docs

# input table
source: docs

# number of LDA topics
default_num_topics: 7

# number of training iterations
iterations: 20

# show top-k significant words for each topics
topk_rank: 50

# To use Japanese tokenizer or not (Please set false for English texts)
japanese: false

# whether to use TF-IDF for feature vector
tfidf: true
